"""Add can_be_rented column to TransportClaim

Revision ID: 6aa521852b60
Revises: 
Create Date: 2024-08-21 09:44:05.992307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aa521852b60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('transport_document')
    with op.batch_alter_table('transport_claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_be_rented', sa.String(length=3), nullable=False))
        batch_op.alter_column('from_location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('to_location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('paid_to',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('plate_no',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('types_of_product',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('number_of_bags',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('quintal',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('unit_price',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('total_price',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('advance_payment',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('remaining_payment',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('requested_by_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('requested_by_signature',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('requested_by_date',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('approved_by_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('approved_by_signature',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('approved_by_date',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_claim', schema=None) as batch_op:
        batch_op.alter_column('approved_by_date',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('approved_by_signature',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('approved_by_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('requested_by_date',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('requested_by_signature',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('requested_by_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('remaining_payment',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('advance_payment',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('total_price',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('unit_price',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('quintal',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('number_of_bags',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('types_of_product',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('plate_no',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('paid_to',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('to_location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('from_location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('can_be_rented')

    op.create_table('transport_document',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('transporter_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cheque_prepared_for', sa.VARCHAR(length=100), nullable=True),
    sa.Column('received_date', sa.VARCHAR(length=100), nullable=True),
    sa.Column('appointment_date', sa.VARCHAR(length=100), nullable=True),
    sa.Column('goods_transported', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone_no', sa.VARCHAR(length=15), nullable=True),
    sa.Column('credit_recipt', sa.VARCHAR(length=200), nullable=True),
    sa.Column('transport_agreement', sa.VARCHAR(length=200), nullable=True),
    sa.Column('way_bill', sa.VARCHAR(length=200), nullable=True),
    sa.Column('weight_scale', sa.VARCHAR(length=200), nullable=True),
    sa.Column('container_inspection', sa.VARCHAR(length=200), nullable=True),
    sa.Column('container_interchange', sa.VARCHAR(length=200), nullable=True),
    sa.Column('grn', sa.VARCHAR(length=200), nullable=True),
    sa.Column('libre', sa.VARCHAR(length=200), nullable=True),
    sa.Column('id_card', sa.VARCHAR(length=200), nullable=True),
    sa.Column('delegation_document', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
